In [1]:
import numpy as np
#import pandas as pd
#from matplotlib import pyplot as plt 

In [3]:
#Creating a NumPy Array

list=[1, 2, 3, 4]

arr=np.array(list)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
# .dtype attribute
#print(arr.dtype) #int 32=4byte로 표현하는 정수타입
lst=[1.1, 1.2, 2.1]
arr=np.array([1, 1.4, "1.1, 1.2, 2.1"]) #U32 에서 U는 데이터 타입 짬뽕을 의미
print(arr.dtype)

<U32


In [13]:
#getsizeof
from sys import getsizeof
lst=[]
print(getsizeof(lst))

arr = np.array(lst)
print(getsizeof(arr))

56
104


In [14]:
#with a list
prices=[30, 25, 40, 20, 20, 35, 50, 35]
price_arr=np.array(prices)

#with a ndarray
price_arr-= 5
print(price_arr)

[25 20 35 15 15 30 45 30]


In [20]:
#masking
a = np.array([10, 2, 3, 4, 5, 9, 8, 7])
mask= a > 5
print(mask)

#selection->논리식을 만족하는 부분집합 구하기
selected=a[a>5]
print(selected)

selected=a[(a>5) | (a<4)] #()묶는거 중요
print(selected)

[ True False False False False  True  True  True]
[10  9  8  7]
[10  2  3  9  8  7]
