In [1]:
import numpy as np

In [22]:
test1=np.array([92, 94, 88, 91, 87])
test2=np.array([79, 100, 86, 93, 91])
test3=np.array([87, 85, 72, 90, 92])
print(test1)
print(test2)
print(test3)

test3_fixed= test3 + 2
print(test3_fixed)

total_grade=test1+test2+test3_fixed
print(total_grade)

final_grade =total_grade /3
print(final_grade)

student_scores=np.array([test1, test2, test3_fixed])
print(student_scores)

jeremy_test2=student_scores[1, 3]
print(jeremy_test2)

manual_adwoa_test1=np.array(student_scores[0, 2], student_scores[0,2]) 
print(manual_adwoa_test1)

print(student_scores[:, 4])

[92 94 88 91 87]
[ 79 100  86  93  91]
[87 85 72 90 92]
[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]
93
88
[87 91 94]
