In [1]:
import numpy as np

In [5]:
def compute_reciprocals(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
        return output
    
values=np.random.randint(1, 10, size=5)
print(values)

compute_reciprocals(values)

[9 8 8 5 4]


array([1.11111111e-001, 1.61323711e-307, 3.65608578e-321, 1.00158201e-311,
       1.33512376e-306])

In [7]:
big_array=np.random.randint(1, 100, size=1000000)

%timeit compute_reciprocals(big_array)

#Vectorized operations
%timeit 1/ big_array

18.3 µs ± 256 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
3.67 ms ± 63.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
#numpy.ufunc

np.random.seed(1)
arr1=np.random.randint(10, size=(5))
arr2=np.random.randint(10, size=(5))
print(arr1,arr2)

arr1=arr1-2
print(arr1)

arr3=arr1+arr2
print(arr3)

arr4=np.random.randint(10, size=(3,5))
print(arr4)

arr5=arr4**2
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [14]:
#ufunce:Array Arithmetic
x=np.arange(4)
print("x= ",x)
print("x+5= ",x+5)


x= [0 1 2 3]
x+5 [5 6 7 8]


In [16]:
#np.abs(): 절댓값 함수
x=np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

x=np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [ ]:
#삼각함수
#theta=np.linspace