In [1]:
import numpy as np

In [3]:
np.arange(3)


<module 'numpy' from 'C:\\Users\\sunmi\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>


In [5]:
"""slicing"""
arr=np.arange(10)
print(arr)

print(arr[3:7])
print(arr[:5])
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [10]:
np.random.seed(2)
arr=np.random.randint(10, size=(6,8))
print(arr)

arr_sub=arr[:2, :2]
print(arr_sub)



[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]
[[8 8]
 [5 4]]
