In [3]:
import numpy as np
import pandas as pd

In [9]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]

print(np.concatenate([x,y,z]))
print(np.vstack([x,y,z])) #세로 방향으로 연결 -> 2차원 배열

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1,2,3])
ser2 = pd.Series(['E', 'F', 'G'], index=[4,5,6])

print(ser1, '\n')
print(ser2)
pd.concat([ser1, ser2])

1    A
2    B
3    C
dtype: object 

4    E
5    F
6    G
dtype: object


1    A
2    B
3    C
4    E
5    F
6    G
dtype: object

In [16]:
def make_df(cols, ind):
    data = {c:[str(c)+str(i) for i in ind]
           for c in cols}
    
    return pd.DataFrame(data, ind)

print(make_df('ABC', [1,2]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2


In [20]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3,4])
print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [25]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0,1])
print(df3)
print(df4)

print(pd.concat([df3, df4], axis=1))

    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
